const DATABASE_USERS="users";
const DATABASE_MATCHES="matches"
const DATABASE_USER_MATCHES="user-matches"
const DATBASE_QUERY_EMAIL="email"

module.exports = { DATABASE_USERS, DATABASE_MATCHES, DATABASE_USER_MATCHES, DATBASE_QUERY_EMAIL }